kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: icedoapp-frontend-canary
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: icedoapp
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: gcr.io/cloud-solutions-images/icedoapp:1.0.0
        resources:
          limits:
            memory: "100Mi"
            cpu: "10m"
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: NATS_HOST
          value: comms-nats
        - name: ENVIRONMENT
          value: canary
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "./icedoapp -p=80"]
        ports:
        - name: frontend
          containerPort: 80
