apiVersion: v1
kind: Service
metadata:
  name: icedoapp-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: icedoapp
    role: frontend
