apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
spec:
  replicas:
  template:
    metadata:
      labels:
        role: monitoring
    spec:
      containers:
      - name: grafana
        image: grafana/grafana 
        resources:
          limits:
            memory: "500Mi"
            cpu: "30m"
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        ports:
        - name: service
          containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-volume
      volumes:
      - name: grafana-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  labels:
    role: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana

