
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana-service
spec:
  replicas:
  template:
    metadata:
      name: service
      labels:
        app: grafana
        role: service
        env: production
    spec:
      containers:
      - name: grafana
        image: grafana/grafana 
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: service
          containerPort: 80
