
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana-service
spec:
  replicas:
  template:
    metadata:
      labels:
        app: grafana
        role: service
        env: production
    spec:
      containers:
      - name: grafana
        image: grafana/grafana 
        resources:
          limits:
            memory: "500Mi"
            cpu: "30m"
        imagePullPolicy: Always
        ports:
        - name: service
          containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-volume
      volumes:
      - name: grafana-volume
        emptyDir: {}
