kind: Service
apiVersion: v1
metadata:
  name: grafana-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana
    role: service

