
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: influxdb-service
spec:
  replicas:
  template:
    metadata:
      name: service
      labels:
        app: influxdb
        role: service
        env: production
    spec:
      containers:
      - name: influxdb
        image: influxdb 
        env:
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        resources:
          limits:
            memory: "500Mi"
            cpu: "30m"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8086
        - name: admin
          containerPort: 8083
