
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: influxdb-service
spec:
  replicas:
  template:
    metadata:
      labels:
        app: influxdb
        role: service
        env: production
    spec:
      containers:
      - name: influxdb
        image: influxdb 
        env:
        - name: INFLUXDB_DB
          value: "jenkins"
        - name: INFLUXDB_ADMIN_USER
          value: "admin"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "supersecretpassword"
        - name: INFLUXDB_USER
          value: "jenkins"
        - name: INFLUXDB_USER_PASSWORD
          value: "secretpassword"
        resources:
          limits:
            memory: "500Mi"
            cpu: "30m"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8086
        - name: admin
          containerPort: 8083
