apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb-deployment
spec:
  replicas:
  template:
    metadata:
      labels:
        app: influxdb
        role: monitoring
    spec:
      containers:
      - name: influxdb
        image: influxdb 
        env:
        - name: INFLUXDB_DB
          value: "jenkins"
        - name: INFLUXDB_ADMIN_USER
          value: "admin"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "supersecretpassword"
        - name: INFLUXDB_USER
          value: "jenkins"
        - name: INFLUXDB_USER_PASSWORD
          value: "secretpassword"
        resources:
          limits:
            memory: "500Mi"
            cpu: "30m"
        ports:
        - name: http
          containerPort: 8086
        - name: admin
          containerPort: 8083
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-volume
      volumes:
      - name: influxdb-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-influxdb-service
  labels:
    role: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: monitoring-influxdb


