apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: comms-nats
spec:
  replicas:
  template:
    metadata:
      labels:
        app: nats
        role: comms
    spec:
      containers:
      - name: nats
        image: nats
        resources:
          limits:
            memory: "100Mi"
            cpu: "10m"
        imagePullPolicy: Always
        ports:
        - name: service
          containerPort: 4222

